"""add vehicle search log

Revision ID: 07c2e719739b
Revises: 3e7f82358ed2
Create Date: 2025-09-18 20:02:23.229135

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from avcfastapi.core.database.sqlalchamey import core
import avcfastapi

# revision identifiers, used by Alembic.
revision: str = "07c2e719739b"
down_revision: Union[str, Sequence[str], None] = "3e7f82358ed2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_search_logs",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("search_term", sa.String(length=100), nullable=False),
        sa.Column("formatted_search_term", sa.String(length=100), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=True),
        sa.Column("longitude", sa.Float(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_vehicle_search_logs_status"),
        "vehicle_search_logs",
        ["status"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_vehicle_search_logs_status"), table_name="vehicle_search_logs"
    )
    op.drop_table("vehicle_search_logs")
    # ### end Alembic commands ###
