"""add device model

Revision ID: 08f4ddbe0bde
Revises: 2a8effd9a7e6
Create Date: 2025-07-18 18:09:43.735547

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from avcfastapi.core.database.sqlalchamey import core


# revision identifiers, used by Alembic.
revision: str = "08f4ddbe0bde"
down_revision: Union[str, Sequence[str], None] = "2a8effd9a7e6"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("device_token", sa.String(length=250), nullable=False),
        sa.Column("device_model", sa.String(length=50), nullable=True),
        sa.Column("platform", sa.String(length=15), nullable=False),
        sa.Column("os_version", sa.String(length=25), nullable=True),
        sa.Column("app_version", sa.String(length=20), nullable=True),
        sa.Column("language_code", sa.String(length=10), nullable=True),
        sa.Column(
            "status", sa.String(length=20), server_default="ACTIVE", nullable=False
        ),
        sa.Column(
            "last_seen", core.db.fields.TZAwareDateTime(timezone=True), nullable=False
        ),
        sa.Column("push_enabled", sa.String(length=20), nullable=False),
        sa.Column("is_deleted", sa.Boolean(), nullable=False),
        sa.Column(
            "deleted_at", core.db.fields.TZAwareDateTime(timezone=True), nullable=True
        ),
        sa.Column(
            "created_at", core.db.fields.TZAwareDateTime(timezone=True), nullable=False
        ),
        sa.Column(
            "updated_at", core.db.fields.TZAwareDateTime(timezone=True), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_devices_device_token"), "devices", ["device_token"], unique=True
    )
    op.create_index(
        op.f("ix_devices_is_deleted"), "devices", ["is_deleted"], unique=False
    )
    op.create_index(op.f("ix_devices_status"), "devices", ["status"], unique=False)
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_index(op.f("ix_devices_status"), table_name="devices")
    op.drop_index(op.f("ix_devices_is_deleted"), table_name="devices")
    op.drop_index(op.f("ix_devices_device_token"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
