"""temp

Revision ID: 265f173e911f
Revises: 041f202683e5
Create Date: 2025-07-05 11:01:42.331240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision: str = '265f173e911f'
down_revision: Union[str, Sequence[str], None] = '041f202683e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_report_status_logs', sa.Column('notes', sa.String(length=255), nullable=True))
    op.drop_column('vehicle_report_status_logs', 'display_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_report_status_logs', sa.Column('display_text', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('vehicle_report_status_logs', 'notes')
    # ### end Alembic commands ###
