"""add is anonymous and is closed on vehicle reports

Revision ID: 2a8effd9a7e6
Revises: ad2204fb7b54
Create Date: 2025-07-09 16:53:17.605467

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from avcfastapi.core.database.sqlalchamey import core


# revision identifiers, used by Alembic.
revision: str = "2a8effd9a7e6"
down_revision: Union[str, Sequence[str], None] = "ad2204fb7b54"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_reports",
        sa.Column("is_anonymous", sa.Boolean(), server_default="false", nullable=False),
    )
    op.add_column(
        "vehicle_reports",
        sa.Column("is_closed", sa.Boolean(), server_default="false", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_reports", "is_closed")
    op.drop_column("vehicle_reports", "is_anonymous")
    # ### end Alembic commands ###
