"""Add vehicle_owner_id

Revision ID: 4d3aeb1644c0
Revises: add_payment_mode_2024
Create Date: 2025-11-14 22:09:20.575004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from avcfastapi.core.database.sqlalchamey import core
from sqlalchemy.dialects import postgresql
import avcfastapi

# revision identifiers, used by Alembic.
revision: str = '4d3aeb1644c0'
down_revision: Union[str, Sequence[str], None] = 'add_payment_mode_2024'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('apartment_permitted_vehicles', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('apartment_permitted_vehicles', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apartment_permitted_vehicles', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apartments', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('apartments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apartments', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cta_events', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cta_events', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_cta_events_user_id'), table_name='cta_events')
    op.add_column('parking_sessions', sa.Column('vehicle_owner_id', sa.UUID(), nullable=True, comment='Owner of the vehicle (if registered in system)'))
    op.drop_index(op.f('ix_parking_sessions_slot_status'), table_name='parking_sessions')
    op.create_index(op.f('ix_parking_sessions_vehicle_owner_id'), 'parking_sessions', ['vehicle_owner_id'], unique=False)
    op.create_foreign_key(None, 'parking_sessions', 'users', ['vehicle_owner_id'], ['id'])
    op.alter_column('shops', 'deleted_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=True)
    op.alter_column('shops', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_vehicle_dues_vehicle_owner'), table_name='vehicle_dues')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_vehicle_dues_vehicle_owner'), 'vehicle_dues', ['vehicle_number', 'slot_owner_id'], unique=False)
    op.alter_column('shops', 'updated_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'created_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('shops', 'deleted_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.drop_constraint(None, 'parking_sessions', type_='foreignkey')
    op.drop_index(op.f('ix_parking_sessions_vehicle_owner_id'), table_name='parking_sessions')
    op.create_index(op.f('ix_parking_sessions_slot_status'), 'parking_sessions', ['slot_id', 'status'], unique=False)
    op.drop_column('parking_sessions', 'vehicle_owner_id')
    op.create_index(op.f('ix_cta_events_user_id'), 'cta_events', ['user_id'], unique=False)
    op.alter_column('cta_events', 'updated_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('cta_events', 'created_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apartments', 'updated_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apartments', 'created_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apartments', 'deleted_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('apartment_permitted_vehicles', 'updated_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apartment_permitted_vehicles', 'created_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('apartment_permitted_vehicles', 'deleted_at',
               existing_type=avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True)
    # ### end Alembic commands ###
