"""add vehicle_number in vehicle location

Revision ID: 7a1c02aafb60
Revises: 07c2e719739b
Create Date: 2025-09-18 21:45:10.482950

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from avcfastapi.core.database.sqlalchamey import core
import avcfastapi

# revision identifiers, used by Alembic.
revision: str = "7a1c02aafb60"
down_revision: Union[str, Sequence[str], None] = "07c2e719739b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_locations",
        sa.Column("vehicle_number", sa.String(length=20), nullable=True),
    )
    op.alter_column(
        "vehicle_locations", "vehicle_id", existing_type=sa.UUID(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "vehicle_locations", "vehicle_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("vehicle_locations", "vehicle_number")
    # ### end Alembic commands ###
