"""add fuel type

Revision ID: ad2204fb7b54
Revises: 41ff89d031d9
Create Date: 2025-07-09 16:18:34.941368

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from avcfastapi.core.database.sqlalchamey import core


# revision identifiers, used by Alembic.
revision: str = "ad2204fb7b54"
down_revision: Union[str, Sequence[str], None] = "41ff89d031d9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicles", sa.Column("fuel_type", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicles", "fuel_type")
    # ### end Alembic commands ###
