"""add additional data to notificatin channel

Revision ID: b23d56ce4a6b
Revises: 0004012a6927
Create Date: 2025-07-26 18:49:22.500540

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from avcfastapi.core.database.sqlalchamey import core
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b23d56ce4a6b"
down_revision: Union[str, Sequence[str], None] = "0004012a6927"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_devices_device_token"), "devices", ["device_token"], unique=False
    )
    op.add_column(
        "notification_channels",
        sa.Column(
            "additional_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Optional: Additional data for the channel (e.g., Other payloads used to generate notification)",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("notification_channels", "additional_data")
    op.drop_index(op.f("ix_devices_device_token"), table_name="devices")
    # ### end Alembic commands ###
