"""change fullname length

Revision ID: cc811b5fd36c
Revises: fbf5daa7696d
Create Date: 2025-07-02 17:35:56.482753

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import core


# revision identifiers, used by Alembic.
revision: str = 'cc811b5fd36c'
down_revision: Union[str, Sequence[str], None] = 'fbf5daa7696d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fullname',
               existing_type=sa.VARCHAR(length=10),
               type_=sa.String(length=120),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'fullname',
               existing_type=sa.String(length=120),
               type_=sa.VARCHAR(length=10),
               existing_nullable=False)
    # ### end Alembic commands ###
