"""add report flag

Revision ID: ce219849935f
Revises: aff2807c7e33
Create Date: 2025-09-10 19:57:27.209929

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import avcfastapi


# revision identifiers, used by Alembic.
revision: str = "ce219849935f"
down_revision: Union[str, Sequence[str], None] = "aff2807c7e33"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vehicle_report_flags",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("subject", sa.String(length=255), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "image",
            avcfastapi.core.storage.sqlalchemy.fields.imagefield.ImageField(),
            nullable=True,
        ),
        sa.Column(
            "created_at",
            avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            avcfastapi.core.database.sqlalchamey.fields.TZAwareDateTime(timezone=True),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["vehicle_reports.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("vehicle_report_flags")
    # ### end Alembic commands ###
