"""add latitude and longitude

Revision ID: fefbf485f3dc
Revises: 97c0d24cf898
Create Date: 2025-07-19 19:24:11.377578

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from avcfastapi.core.database.sqlalchamey import core


# revision identifiers, used by Alembic.
revision: str = "fefbf485f3dc"
down_revision: Union[str, Sequence[str], None] = "97c0d24cf898"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "vehicle_reports", sa.Column("latitude", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "vehicle_reports", sa.Column("longitude", sa.String(length=20), nullable=True)
    )
    op.add_column(
        "vehicle_reports", sa.Column("location", sa.String(length=255), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("vehicle_reports", "location")
    op.drop_column("vehicle_reports", "longitude")
    op.drop_column("vehicle_reports", "latitude")
    # ### end Alembic commands ###
