from apps.api.vehicle.models import *
from apps.api.chat.models import *
from apps.api.user.models import *
from apps.api.vehicle.report.models import *
from apps.api.device.models import *
from apps.api.notification.models import *
from apps.api.shop.models import *
from apps.api.analytics.models import *
from apps.api.apartment.models import *
from apps.api.parking.models import *
from apps.api.organization.models import *